config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "videos#index"

  resources :users, only: %i[create show]
  resources :videos, only: %i[create update destroy edit]

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/share', to: 'videos#new'

  resource :sessions, only: %i[create destroy]

  # Mount ActionCable server.
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  password_digest :string
#  username        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_username  (username) UNIQUE
#
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :videos, dependent: :destroy
end

app/models/video.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: videos
#
#  id         :bigint           not null, primary key
#  title      :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_videos_on_user_id  (user_id)
#
class Video < ApplicationRecord
  belongs_to :user
  after_create :broadcast_video
  validate :video_exists_on_youtube

  def extract_video_id
    url.match(%r{youtu(?:\.be|be\.com)/(?:watch\?v=)?([\w-]{11})})&.[](1)
  end

  private

  def broadcast_video
    ActionCable.server.broadcast('videos_channel', rendered_video)
  end

  def rendered_video
    title = YoutubeService.list_videos('snippet', id: extract_video_id).items.first.snippet.title
    update(title:) if title
    ApplicationController.renderer.render(
      partial: 'videos/video',
      locals: { video: self }
    )
  end

  def video_exists_on_youtube
    video = YoutubeService.list_videos('snippet', id: extract_video_id).items.first
    return unless video.nil?

    errors.add(:url, 'does not exist on YouTube')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    return unless session[:user_id]

    @user = User.find(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'You have been logged out.'
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Logged in successfully.'
    else
      redirect_to login_path, alert: 'Invalid username or password.'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authorized, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User was successfully created.'
      redirect_to @user
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  before_action :authorized, only: %i[new create edit update]
  before_action :find_video, only: %i[edit update]

  def index
    @videos = Video.all
    video_ids = @videos.map(&:extract_video_id).compact

    return unless video_ids.any?

    begin
      response = YoutubeService.list_videos('snippet', id: video_ids.join(','))
      @video_details = response.items
    rescue Google::Apis::ClientError => e
      Rails.logger.error e.message
    end
  end

  def new
    @video = Video.new
  end

  def edit; end

  def update
    if @video.update(video_params)
      redirect_to root_path, notice: 'Video updated successfully!'
    else
      render :edit
    end
  end

  def create
    @video = current_user.videos.build(video_params)
    if @video.save
      redirect_to root_path, notice: 'Video added successfully!'
    else
      render :new
    end
  end

  private

  def find_video
    @video = Video.find_by(id: params[:id])
  end

  def video_params
    params.require(:video).permit(:url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"  %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <br>
    <% if logged_in? %>
      <%= button_to "Logout", sessions_path, method: :delete %>
    <% end %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Username" %>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to the page of <%= @user.username %></h1>

<% if current_user == @user %>
  <h3>This is my page!!!</h3>
  <%= link_to 'Share Video', share_path, class: 'btn btn-primary' %>
<% end %>

app/views/videos/_form.html.erb
<%= form_with model: video do |f| %>
  <div class="field">
    <%= f.label :url, "YouTube URL" %>
    <%= f.text_field :url %>
  </div>
  <%= f.submit %>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>" class="video">
  <span><%= video.user.username %></span>
  <span><%= video.title %></span>
</div>

app/views/videos/edit.html.erb
<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<h1 class="center-content">Videos</h1>
<div data-controller="videos">
  <div data-videos-target="container">
    <% @videos.each do |video| %>
      <% video_details = @video_details.find { |details| details.id == video.extract_video_id } %>
      <% if video_details %>
        <li style="display: grid; grid-template-columns: 1fr 6fr; gap: 20px;">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= video.extract_video_id %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div>
            <%= link_to video_details.snippet.title, video.url %> (shared by <%= video.user.username %>)
            <p><%= video_details.snippet.description.truncate(100) %></p>
            <% if current_user == video.user %>
              <%= link_to 'Edit Video', edit_video_path(video), class: 'btn btn-primary' %>
            <% end %>
          </div>
        </li>
      <% end %>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<%= render 'form', video: @video %>